apps/home/urls.py
from django.urls import path, include

from apps.home import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete-obj/<path:key>/', views.DeleteBucketObjectView.as_view(), name='delete_obj_bucket'),
    path('download-obj/<path:key>/', views.DownloadBucketObjectView.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category-filter'),
    path('bucket/', include(bucket_urls)),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/forms.py
from django import forms


class UploadBucketObjectForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput)

apps/home/views.py
import os

from django.conf import settings
from django.contrib import messages
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.shortcuts import render, redirect
from django.views import View

from apps.home.forms import UploadBucketObjectForm
from apps.home.tasks import get_all_bucket_objects_task, delete_object_task, download_object_task, upload_object_task
from apps.products.models import Product, Category
from apps.utils.custom_mixins import IsAdminUserMixin


class HomeView(View):
    def get(self, request, category_slug=None):
        if category_slug:
            products = Product.objects.filter(category__slug=category_slug)
        else:
            products = Product.objects.filter(available=True)
        categories = Category.objects.filter(active=True, is_sub=False)
        context = {
            'products': products,
            'categories': categories,
        }
        return render(request, 'home/home.html', context)


class BucketHomeView(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'
    form_class = UploadBucketObjectForm

    def get(self, request):
        objects = get_all_bucket_objects_task()
        context = {
            'objects': objects
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            file_name = default_storage.save(file.name, ContentFile(file.read()))
            temp_file_path = os.path.join(settings.MEDIA_ROOT, file_name)

            upload_object_task.delay(temp_file_path)
            messages.success(request, 'your object will be upload soon ', extra_tags='info')
        else:
            messages.error(request, 'Invalid Credentials', extra_tags='error')

        return redirect('home:bucket')


class DeleteBucketObjectView(IsAdminUserMixin, View):
    def get(self, request, key):
        delete_object_task.delay(key)
        messages.success(request, 'your object will be delete soon ', extra_tags='info')
        return redirect('home:bucket')


class DownloadBucketObjectView(IsAdminUserMixin, View):
    def get(self, request, key):
        download_object_task.delay(key)
        messages.success(request, 'your object will be download soon ', extra_tags='info')
        return redirect('home:bucket')

templates/home/bucket.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}

{% block content %}
    <br>
    <label for="upload-obj-bucket">choose file to upload:</label>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_file">Choose a file:</label>
        <input type="file" name="file" id="id_file">
        <input type="submit" id="upload-obj-bucket" value="Upload">
    </form>
    <br>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ obj.Key }}</td>
                <td>{{ obj.Size|filesizeformat }}</td>
                <td><a href="{% url 'home:download_obj_bucket' obj.Key %}">download</a></td>
                <td><a href="{% url 'home:delete_obj_bucket' obj.Key %}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/home/home.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}
    {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
                    aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% for sub_cat in category.sub_categories.all %}
                    <li><a class="dropdown-item" href="{{ sub_cat.get_absolute_url }}">{{ sub_cat.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <br><br>

    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block">
            <img src="{{ product.image.url }}" class="card-img-top">
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}