apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserVerifyOtpView.as_view(), name='verify_otp_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogOutView.as_view(), name='user_logout'),
]

apps/home/urls.py
from django.urls import path, include

from apps.home import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete-obj/<path:key>/', views.DeleteBucketObjectView.as_view(), name='delete_obj_bucket'),
    path('download-obj/<path:key>/', views.DownloadBucketObjectView.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category-filter'),
    path('bucket/', include(bucket_urls)),

]

apps/orders/urls.py
from django.urls import path

from apps.orders import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('coupon/apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %} 

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if not request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
                <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            {% else %}
                <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
                {% if request.user.is_admin %}
                    <a class="nav-link active" href="{% url 'home:bucket' %}">Bucket</a>
                {% endif %}
            {% endif %}
            <a class="nav-link active" href="{% url 'orders:cart' %}">Cart {{ cart|length }}</a>

        </div>
    </div>
</nav>